apiVersion: apps/v1
kind: Deployment
metadata:
  name: localai
  namespace: localai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localai
  template:
    metadata:
      labels:
        app: localai
    spec:
      containers:
        - name: localai
          image: localai/localai:latest
          args:
            - "--address=0.0.0.0:4000"
          ports:
            - containerPort: 4000