apiVersion: v1
kind: Service
metadata:
  name: localai-service
  namespace: localai
spec:
  selector:
    app: localai
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: LoadBalancer