# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "azurerm" {
    container_name       = "backend"
    key                  = "02-cluster-addons/terraform.tfstate"
    resource_group_name  = "DefaultResourceGroup-EUS"
    storage_account_name = "lyriqseleterraform"
  }
}
