apiVersion: v1
kind: Service
metadata:
  name: localai-service
  namespace: localai
spec:
  selector:
    app: localai
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer