apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: localai
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/selelyriq/terraform-aks-llm.git
    path: app-manifests/01-localai
    targetRevision: 1.2.3
    helm:
      values: |
        service:
          type: LoadBalancer
  destination:
    server: https://kubernetes.default.svc
    namespace: localai