name: Helm Test and Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: 'latest'

      - name: Set up KinD cluster
        uses: helm/kind-action@v1.10.0

      - name: Linting Helm chart
        run: helm lint app-manifests/01-localai/localai

      - name: Install Trivy
        run: |
          sudo apt-get install wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy
      
      - name: Scan Helm chart with Trivy
        run: trivy config --exit-code 0 --severity UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL app-manifests/01-localai/localai

      - name: Render Helm template (simulate ArgoCD rendering)
        run: helm template my-release app-manifests/01-localai/localai --values app-manifests/01-localai/localai/values.yaml  

      - name: Install Helm chart
        run: helm install my-release app-manifests/01-localai/localai --wait

      - name: Test Helm chart
        run: helm test my-release

      - name: Validate ArgoCD Application YAML
        run: |
          kubectl apply --dry-run=client -f app-manifests/03-argocd/01-argocd-config.yaml

      - name: Save rendered manifests
        run: |
          helm template my-release app-manifests/01-localai/localai \
            --values app-manifests/01-localai/localai/values.yaml > rendered.yaml

      - name: Upload rendered manifests
        uses: actions/upload-artifact@v4
        with:
          name: rendered-helm-output
          path: rendered.yaml