name: Validate K8s Manifests

on:
  pull_request:
    paths:
      - 'app-manifests/01-localai/templates/**'
      - 'app-manifests/02-photoprisma/**'
      - 'app-manifests/03-argocd/**'
  push:
    branches:
      - main

jobs:
  validate-k8s-manifests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Validate syntax & schema
      - name: Install kubeconform
        run: |
          curl -L https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz | tar xz
          sudo mv kubeconform /usr/local/bin/
      - name: Run kubeconform
        run: |
          kubeconform -strict -summary -output text -kubernetes-version 1.27 k8s-manifests/

      # Scan with Trivy
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy
      - name: Run Trivy config scan
        run: |
          trivy config --severity HIGH,CRITICAL k8s-manifests/

      # Policy checks with Conftest
      - name: Install Conftest
        run: |
          curl -L https://github.com/open-policy-agent/conftest/releases/latest/download/conftest_Linux_x86_64.tar.gz | tar xz
          sudo mv conftest /usr/local/bin/
      - name: Run Conftest
        run: |
          conftest test k8s-manifests/

      # Upload SARIF to GitHub Security tab
      - name: Run Trivy with SARIF output
        run: |
          trivy config --format sarif --output trivy-results.sarif k8s-manifests/
      - name: Upload SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: trivy-results.sarif