name: Terragrunt CI (dev)

on:
  pull_request:
    branches:
      - main
    paths:
      - 'terragrunt/**'
      - '.github/workflows/terraform-dev.yaml'

permissions: # Explicitly declare minimal required permissions
  id-token: write
  contents: read

jobs:
  checkov:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@v12
        with:
          # This will add both a CLI output to the console and create a results.sarif file
          output_format: cli,sarif
          output_file_path: console,results.sarif
        
  format:
    needs: checkov
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v3.0.2
      - name: Terragrunt Format
        run: terragrunt hclfmt --terragrunt-check
        working-directory: terragrunt

  terragrunt-validate:
    needs: format
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v3.0.2
      - name: Configure Azure Credentials
        uses: azure/login@v1
        with:
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
      - name: Terragrunt Init
        run: terragrunt run-all init -reconfigure
        working-directory: terragrunt/environments/dev
      - name: Terragrunt Validate
        run: terragrunt run-all validate
        working-directory: terragrunt/environments/dev

  terragrunt-plan:
    needs: terragrunt-validate
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v3.0.2
      - name: Configure Azure Credentials
        uses: azure/login@v1
        with:
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
      - name: Terragrunt Init
        run: terragrunt run-all init -reconfigure
        working-directory: terragrunt/environments/dev
      - name: Terragrunt Plan
        run: terragrunt run-all plan -out=plan.tfplan
        working-directory: terragrunt/environments/dev
        env:
          TF_LOG: DEBUG
      - name: Archive plan files
        run: |
          tar -czvf pr-${{ github.event.pull_request.number }}.tar.gz \
          -C terragrunt/environments/dev \
          --exclude='**/.terragrunt-cache' \
          .
        
      - name: Upload Terraform Plan to Azure
        uses: azure/cli@v1
        with:
          inlineScript: |
            az storage blob upload \
              --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} \
              --container-name tfplans \
              --name pr-${{ github.event.pull_request.number }}.tar.gz \
              --file pr-${{ github.event.pull_request.number }}.tar.gz \
              --auth-mode login \
              --overwrite
