name: Terragrunt Apply (dev)

on:
  push:
    branches:
      - main
    paths:
      - 'terragrunt/**'
      - '.github/workflows/terraform-apply.yaml'

permissions: # Explicitly declare minimal required permissions
  id-token: write
  contents: read

jobs:
  terragrunt-apply:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v3.0.2
        with:
          terragrunt-version: v0.58.11
      - name: Configure Azure Credentials
        uses: azure/login@v1
        with:
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
      - name: Terragrunt Init
        run: terragrunt run-all init -reconfigure
        working-directory: terragrunt/environments/dev
      - name: Terragrunt Apply
        run: terragrunt run-all apply -auto-approve
        working-directory: terragrunt/environments/dev
        env:
          TF_LOG: DEBUG
