name: Terraform CD (main)

on:
  push:
    branches:
      - main
    paths:
      - 'terraform-patterns/**'
      - '.github/workflows/terraform-apply.yaml'

permissions: # Explicitly declare minimal required permissions
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Configure Azure Credentials
        uses: azure/login@v1
        with:
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
      - name: Download Terraform Plan from Azure
        uses: azure/cli@v1
        with:
          inlineScript: |
            az storage blob download \
              --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} \
              --container-name tfplans \
              --name ${{ github.sha }}/plan.tfplan \
              --file terraform-patterns/standard/plan.tfplan \
              --auth-mode login
      - name: Terraform Init
        run: terraform init
        working-directory: terraform-patterns/standard
      - name: Terraform Apply
        run: terraform apply plan.tfplan
        working-directory: terraform-patterns/standard
        env:
          TF_LOG: DEBUG